using Microsoft.CodeAnalysis;

/* ConfigLoaderGenerator is distributed under [CC BY-NC-SA 4.0 INTL](https://creativecommons.org/licenses/by-nc-sa/4.0/).                 *\
 * You are free to redistribute, share, adapt, etc. as long as the original author (stupid_chris/Christophe Savard) is properly, clearly, *
\* and explicitly credited, that you do not use this material to a commercial use, and that you distribute it under the same license.     */

namespace ConfigLoaderGenerator;

[Generator]
public class LoadFromConfigGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        string source =
"""
// <auto-generated/>
using UnityEngine;

namespace GeneratedCode
{
    public static class Test
    {
        public static void Foo()
        {
            Debug.Log("Generator says: Foobar!");
        }
    }
}
""";
        context.AddSource("GenerateTest.generated.cs", source);
    }
}
